# Generated by Django 3.0.7 on 2020-06-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedCaseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expire_at', models.DateTimeField()),
                ('is_visible', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='GeospatialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finshed', models.BooleanField(default=False)),
                ('finshed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QurantineCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='RedisBatchManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finshed', models.BooleanField(default=False)),
                ('is_quarantine_batches_completed', models.BooleanField(default=False)),
                ('is_location_batches_completed', models.BooleanField(default=False)),
                ('location_points', models.PositiveIntegerField(blank=True, default=0)),
                ('qurantine_points', models.PositiveIntegerField(blank=True, default=0)),
                ('location_batches', models.PositiveIntegerField(blank=True, default=0)),
                ('qurantine_batches', models.PositiveIntegerField(blank=True, default=0)),
                ('location_completed_batches', models.PositiveIntegerField(blank=True, default=0)),
                ('qurantine_completed_batches', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuarantineCenterBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('batch_no', models.PositiveIntegerField()),
                ('range_start', models.PositiveIntegerField()),
                ('range_end', models.PositiveIntegerField()),
                ('batch_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19nearyou.RedisBatchManager')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmedCaseLocationBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('batch_no', models.PositiveIntegerField()),
                ('range_start', models.PositiveIntegerField()),
                ('range_end', models.PositiveIntegerField()),
                ('batch_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covid19nearyou.RedisBatchManager')),
            ],
        ),
        migrations.CreateModel(
            name='AddToFileNewAndExpireOldCovid19Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_file_created', models.BooleanField(default=False)),
                ('is_points_removed', models.BooleanField(default=False)),
                ('is_finshed', models.BooleanField(default=False)),
                ('url', models.URLField(null=True)),
                ('geospatialfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covid19nearyou.GeospatialFile')),
            ],
        ),
    ]
