

#GEOSPATIAL DATA
GEOSPATIAL_DATA_KEY = 'COVID19POINTS'
#COIVD19 GEOSPATIAL EXPIRESET
COVID19_GEOSPATIAL_POINTS_EXPIRE_DATA_KEY = 'EXPR_AND_POINTS'



LOCATION_OBJECT_KEY = 'location-id:'
GEOSPATIAL_QUARANTINE_DATA_KEY = 'COVID19QUARANTINE'
QUARANTINE_OBJECT_KEY = 'quarantine-id:'